//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactWebForms {
    
    
    public partial class _Default {
        
        /// <summary>
        /// ReactComponentSelector1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ReactWebForms.Controls.ReactComponentSelector ReactComponentSelector1;
        
        /// <summary>
        /// ReactComponentSelector2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ReactWebForms.Controls.ReactComponentSelector ReactComponentSelector2;
        
        /// <summary>
        /// ReactComponentSelector3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ReactWebForms.Controls.ReactComponentSelector ReactComponentSelector3;
    }
}
